### PR TITLE
Templates for using datalad/release-action

### LINKED ISSUE #48: Make use of datalad/release-action
Now that we test driven it in DataLad proper, let's use in extensions.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #48.

### CODE REVIEW

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
Looks good to me. @mih any suggestions/objections?

**Review by mih — COMMENTED** [review]
I am not sure what to add in the documentation re tailoring for a dedicated extension. I would have no idea what to do personally. We could move the files in `.github` aside and turn them into a "template" or "sketch". Or add documentation on what they try to achieve. Either way is fine with me. Only the combination of active and no docs should be avoided. To clarify, I am mostly talking about the workflows. The `changelog.d` is dead-weight for people who don't use `scriv`, but it also does nothing in that case.

**Comment by yarikoptic** [comment]
> Only the combination of active and no docs should be avoided.

agree

> The `changelog.d` is dead-weight for people who don't use `scriv`, but it also does nothing in that case.

not really -- scriv would be used by action, so it would be "editable metadata for the release action" even if they don't use `scriv` directly.

@jwodder, please

- initiate CONTRIBUTING.md here which would have a section on releasing which describes annotation of PRs etc, similar to what we have in DataLad https://github.com/datalad/datalad/blob/maint/CONTRIBUTING.md#releasing-with-github-actions-auto-and-pull-requests . While at it, also please fix that description in DataLad itself which still refers to no longer used `auto`.
- refer to CONTRIBUTING.md within README.md

**Comment by jwodder** [comment]
@yarikoptic Note that DataLad's `CONTRIBUTING.md` contains up-to-date information on the `master` branch but not on the `maint` branch, as https://github.com/datalad/datalad/pull/7204 was made against `master` (despite being after the default branch was changed).  There are also various other differences between the two branches' versions of the file.  What exactly should be done about this, and by whom?

**Comment by jwodder** [comment]
@yarikoptic 

> refer to CONTRIBUTING.md within README.md

Refer to it how?  What exactly should be said?

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> > refer to CONTRIBUTING.md within README.md
> 
> Refer to it how? What exactly should be said?

in datalad we have

```
# Contributing

See [CONTRIBUTING.md](CONTRIBUTING.md) if you are interested in internals or
contributing to the project.
```

which sounds good to paste here.

> There are also various other differences between the two branches' versions of the file. What exactly should be done about this, and by whom?

oh ok, nevermind then... @bpoldrack soon will cut new major minor release so it would become up to date... if doesn't happen then we would bring it up again.

**Comment by yarikoptic** [comment]
ok, I think this PR is ready.  Added it to tomorrow's meetup agenda to seek feedback/blessing

**Comment by mih** [comment]
This is reading an extension for using the release action, but does not impose its use. All good with me. Thx!

**Pull request merged**
